global_frame: odom

rolling_window: true
publish_frequency: 5.0

width: 4.0
height: 4.0
resolution: 0.025

plugins:
 - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
 - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
 - {name: range_sensor_layer,   type: "range_sensor_layer::RangeSensorLayer"}
